config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :forum_topics do
    resources :posts
  end

  resources :posts_searches, only:[:index]

  root to: 'forum_topics#index'

end

app/models/forum_topic.rb
class ForumTopic < ActiveRecord::Base
  validates :title, presence: true, uniqueness: true

  belongs_to :user
  has_many :posts, dependent: :destroy
end

app/models/markdown.rb
class Markdown
  def transformed_content(text)
    renderer_options = {
      filter_html:     false,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
    }

    markdown_options = {
      autolink:           true,
      strikethrough:      true,
      fenced_code_blocks: true,
    }

    renderer = HTMLWithPygments.new(renderer_options)
    markdown = Redcarpet::Markdown.new(renderer, markdown_options)

    markdown.render(text).html_safe
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :content, presence: true

  belongs_to :forum_topic
  belongs_to :user

  mount_uploader :post_image, PostImageUploader

  searchable do
    text :content
  end

  delegate :title, to: :forum_topic
  delegate :username, to: :user
end

app/models/user.rb
class User < ActiveRecord::Base
  include Gravtastic
  gravtastic

  before_save { email.downcase! }

  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :confirmable,
  :authentication_keys => [:login]

  validates :username, presence: true, uniqueness: { case_sensitive: false }

  has_many :forum_topics
  has_many :posts

  attr_accessor :login

  mount_uploader :avatar, AvatarUploader

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where(["(username) = :value OR (email) = :value",
        { :value => login.downcase }]).first
    else
      where(conditions.to_hash).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u|
        u.permit(
          :username,
          :email,
          :password,
          :password_confirmation,
          :remember_me,
        )
      }
      devise_parameter_sanitizer.for(:sign_in) { |u|
        u.permit(
          :login,
          :username,
          :email,
          :password,
          :remember_me,
          )
      }
      devise_parameter_sanitizer.for(:account_update) { |u|
        u.permit(
          :username,
          :email,
          :password,
          :current_password,
          :password_confirmation,
          :github_account,
          :twitter_account,
          :bio,
          :position,
          :avatar,
          )
      }
    end
end

app/controllers/forum_topics_controller.rb
class ForumTopicsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @forum_topics = ForumTopic.all
  end

  def new
    @forum_topic =  ForumTopic.new
  end

  def create
    @forum_topic =  ForumTopic.new(forum_topic_params)
    @forum_topic = current_user.forum_topics.new(forum_topic_params)
    if @forum_topic.save
      redirect_to @forum_topic
    else
      render "new"
    end
  end

  def show
    @forum_topic = ForumTopic.find(params[:id]).decorate
  end

  def update
    @forum_topic = ForumTopic.find(params[:id])
    if @forum_topic.update(forum_topic_params)
      flash[:notice] = "This Forum Topic has been updated"
    else
      flash[:alert] = "There was an error updating this Forum Topic"
    end
    redirect_to @forum_topic
  end

  private

  def forum_topic_params
    params.require(:forum_topic).permit(:title, :archived)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_forum_topic
  before_action :authenticate_user!

  def new
    @post = Post.new.decorate
  end

  def create
    @post = @forum_topic.posts.new(post_params).decorate
    @post.user = current_user
    if previewed? || !@post.save
      render "new"
    else
      flash[:notice] = "Post successfully created"
      redirect_to forum_topic_path(@forum_topic.id)
    end
  end

  def show
    @post = @forum_topic.posts.find(params[:id]).decorate
  end

  private

  def find_forum_topic
    @forum_topic = ForumTopic.find(params[:forum_topic_id])
  end

  def post_params
    params.require(:post).permit(:content, :forum_topic_id, :post_image, :commit)
  end

  def previewed?
    params[:preview_button]
  end
end

app/controllers/posts_searches_controller.rb
class PostsSearchesController < ApplicationController
  before_action :authenticate_user!

  def index
    @query = Post.search do
      fulltext params[:search]
    end
    @posts = @query.results
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
  end

  def sign_in
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user_path user
    else
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/forum_topics/index.html.erb
<h5>Forum Topics Index</h5>

  <% @forum_topics.each do |forum_topic| %><br />
  <%= link_to forum_topic.title, forum_topic_path(forum_topic.id) %>
  <% end %>

app/views/forum_topics/new.html.erb
<%= form_for @forum_topic do |f| %>

  <% if @forum_topic.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@forum_topic.errors.count, "error") %> prohibited
        this forum_topic from being saved:
      </h2>
      <ul>
        <% @forum_topic.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/forum_topics/show.html.erb
<h1>You're at the Forum Topic Page </h1>
<h1><%= @forum_topic.title %></h1>
<% @forum_topic.posts.each do |post| %><br />
  <%= post.user.thumbnail %>
  <%= post.user.username %>:
  <%= post.formatted_content %>
  <%= post.accompanying_image %>
  <% end %>
<% if @forum_topic.archived? %>
  <%= button_to "Un-Archive", forum_topic_path(@forum_topic), { method: :patch,
  params: { "forum_topic[archived]" => false } } %>
<% else %>
  <%= button_to "Archive", forum_topic_path(@forum_topic), { method: :patch,
  params: { "forum_topic[archived]" =>  true } } %>
  <%= button_to "Create a new post", new_forum_topic_post_path(@forum_topic), method: :get %>
<% end %>

app/views/layouts/_header.html.erb
<h2>Big Nerd Ranch Forum</h2>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/users/sign_in">Home</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
            <li><%= link_to "Profile", edit_user_registration_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
            <li><%= link_to "Create New Forum Topic", new_forum_topic_path %></li>
            <li><%= link_to "View All Forum Topics", forum_topics_path %></li>
            <li><%= form_tag posts_searches_path, :method => :get do %>
                <%= text_field_tag :search, params[:search] %>
                <%= submit_tag "Search", :name => nil %></li>
            <% end %>
        <% else %>
            <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_notices.html.erb
<% if flash[:notice] %>
  <div class="alert-box">
    <div class="alert alert-notice"><%= flash[:notice] %></div>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert-box">
    <div class="alert alert-notice"><%= flash[:alert] %></div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Forum</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <%= render 'layouts/notices' %>
  <%= yield %>
</body>
</html>

app/views/posts/index.html.erb
<%= form_tag forum_topic_posts_path, :method => :get do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search", :name => nil %>
<% end %>

app/views/posts/new.html.erb
<%= @forum_topic.title %>
<%= form_for ([@forum_topic, @post]) do |f| %><br />

  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %>
        prohibited this post from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    <% end %>

  <% if params[:preview_button] %>
    <%= @post.formatted_content %><br />
    <%= @post.accompanying_image %><br />

    <%= f.label :content %><br />
    <%= f.text_area :content %><br />

    <%= f.label :post_image %><br />
    <%= f.file_field :post_image %><br />

    <%= f.submit "Submit" %>
  <% else %>

    <%= f.label :content %><br />
    <%= f.text_area :content %><br />

    <%= f.label :post_image %><br />
    <%= f.file_field :post_image %><br />

    <%= f.submit "Submit" %>
    <%= f.submit "Preview", name: "preview_button" %>

  <% end %>

<% end %>

app/views/posts/show.html.erb
<h1><%= @forum_topic.title %></h1>
<%= form_for ([@forum_topic, @post]) do |f| %><br />
  <%= @post.formatted_content %>
  <%= @post.accompanying_image %>
<% end %>
  <%= link_to "Back to Forum Topic", forum_topic_path(@forum_topic.id) %>

app/views/posts_searches/index.html.erb
<% @posts.each do |post| %>
  <p><%= link_to post.title, forum_topic_post_path(post.forum_topic,post) %></p>
      <p><%= post.username %>: <%= post.content %></p>
<% end %>

app/views/users/show.html.erb
<h1>Big Nerd Ranch Forum</h1>
<h3>Welcome <%= @user.email %></h3>

<h3><%= link_to 'Create a new forum topic', new_forum_topic_path %></h3>